# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6213fc5d8899dd7fb5fb0f4de3317081894ed7b756cd35680d0e4a927008769ed3f0811a4bafea52f16616e6e388b9fa6a76afcc53f61a6148e9e75e43e65ead

test:
  secret_key_base: 4dd321268d5d4938109c1d716e04e9411f26cf252204c715735236954d80baf1c390c36a75ec91b2e3428d57553893e9bc2a9055becd915a6a7339a62529b9bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
